- name: Copy config *.yml
  template: src={{ item}}.yml.j2 dest={{app_path}}/shared/config/{{item}}.yml
  with_items:
    - database
    - erly_meetings
    - secrets
    - honeybadger

- name: Copy sidekiq_pusher
  copy: src=sidekiq_pusher dest={{app_path}}/shared/bin/sidekiq_pusher owner={{ deploy_user }} group={{ deploy_user }} mode=0754
