---
- name: EC2 ELK
  hosts: 
    - aws_elk
  sudo: yes 
  remote_user: ubuntu
  gather_facts: True
  roles:
    - { role: 'palkan.common_setup', tags: ['common'] }
    - { role: 'palkan.deploy_user', tags: ['user'] }
    - { role: 'palkan.elk', tags: ['elk'] }
