- src: palkan.common_setup
- src: palkan.deploy_user
- src: palkan.tmpreaper
- src: palkan.ruby
- src: palkan.postgresql
- src: palkan.redis
- src: palkan.nodejs
- src: palkan.nginx
- src: palkan.phantomjs
- src: palkan.texlive
- src: palkan.logstash-forwarder
- src: palkan.ssl_certs
- src: redouane.golang
- src: alekseenkoss77.hivemind
- src: alekseenkoss77.docker
- src: alekseenkoss77.filebeat
- src: alekseenkoss77.discourse
- src: alekseenkoss77.monit
- src: nickhammond.logrotate
- src: salex-ansible.influxdb
- src: salex-ansible.telegraf
- src: salex-ansible.chronograf
- src: salex-ansible.kapacitor
