---
- name: EC2 Nginx prod
  hosts: 
    - aws_nginx
  sudo: yes 
  remote_user: ubuntu
  gather_facts: True
  roles:
    - { role: 'palkan.common_setup', tags: ['initial'] }
    - { role: 'palkan.deploy_user', tags: ['user'] }
    - { role: 'palkan.ruby', tags: ['ruby'] }
    - { role: 'palkan.redis', tags: ['redis'] }
    - { role: 'alekseenkoss77.monit', tags: ['monit'] }
