---
- name: Development setup
  hosts: development
  user: vagrant
  sudo: true
  vars_files:
    - group_vars/development.yml
  roles:
    - common_setup
    - ruby
    - postgres
    - redis
    - nodejs
    - influxdb
    - tb_deps