---
- name: CI server
  hosts:
    - ci
  sudo: yes
  remote_user: root
  gather_facts: True
  roles:
    - { role: 'palkan.common_setup', tags: ['initial'] }
    - { role: 'palkan.deploy_user', tags: ['user'] }
    - { role: 'palkan.ruby', tags: ['ruby'] }
    - { role: 'palkan.postgresql', tags: ['postgres'] }
    - { role: 'palkan.redis', tags: ['redis'] }
    - { role: 'palkan.nodejs', tags: ['nodejs'] }
    - { role: 'palkan.nginx', tags: ['nginx'] }
    - { role: 'palkan.tmpreaper', tags: ['tb_deps'] }
    - { role: tb_deps, tags: ['tb_deps'] }
