---
- name: EC2 production
  hosts: aws-production
  sudo: yes 
  remote_user: ubuntu
  vars_files:
    - group_vars/production.yml
  gather_facts: True
  roles:
    - { role: common_setup, tags: ['initial'] }
    - { role: deploy_user, tags: ['user'] }
    - { role: ruby, tags: ['ruby'] }
    - { role: postgres, tags: ['postgres'] }
    - { role: redis, tags: ['redis'] }
    - { role: nodejs, tags: ['nodejs'] }
    - { role: nginx, tags: ['nginx'] }
    - { role: tmpreaper, tags: ['tb_deps'] }
    - { role: texlive, tags: ['latex'] }
    - { role: tb_deps, tags: ['tb_deps'] }
    - { role: tb_prepare, tags: ['tb_prepare'] }