- name: Download ruby
  get_url: "url={{ruby_url}} dest={{ruby_tmp_path}}.tar" 
- name: Extract ruby
  command: tar -zxf "{{ruby_tmp_path}}.tar"
- name: Make, configure, and install ruby
  command: "{{item}} chdir={{ruby_name}}"
  with_items:
    - ./configure
    - make
    - sudo make install
    
- name: Install bundler
  command: sudo gem install {{ item.name }}
  with_items:
   - { name: 'bundler'}

- name: Update ruby permissions  
  command: "sudo chown -R {{deploy_user}} /usr/local/lib/ruby"