---
- name: Checking installed version of node.js
  shell: /usr/bin/test "$(node -v 2> /dev/null)" = v{{ node_version }}
  register: _installed
  ignore_errors: True

- name: Purge previous
  apt: pkg=node state=absent
  when: _installed.rc == 1

- name: Fetching node.js source
  get_url: url=http://nodejs.org/dist/v{{ node_version }}/{{ node_tarball }} dest=/tmp/
  when: _installed.rc == 1

- name: Unpack node.js tarball
  command: tar zxf {{ node_tarball }} chdir=/tmp
  when: _installed.rc == 1

- name: Configure
  shell: /usr/bin/python ./configure --prefix={{ node_path }} chdir=/tmp/{{ node_prefix }}
  when: _installed.rc == 1

- name: Make
  shell: /usr/bin/make chdir=/tmp/{{ node_prefix }}/
  when: _installed.rc == 1

- name: Make install
  shell: /usr/bin/make install chdir=/tmp/{{ node_prefix }}/
  when: _installed.rc == 1
