---
- name: Checking installed version of ruby
  shell: ruby -v | grep -o "ruby {{ ruby_version }}"
  register: _installed
  ignore_errors: True

- name: Download ruby
  get_url: "url={{ruby_url}} dest={{ruby_tmp_path}}.tar"
  when: _installed.rc == 1 
- name: Extract ruby
  command: tar -zxf "{{ruby_tmp_path}}.tar"
  when: _installed.rc == 1
- name: Make, configure, and install ruby
  command: "{{item}} chdir={{ruby_name}}"
  with_items:
    - ./configure
    - make
    - sudo make install
  when: _installed.rc == 1
    
- name: Install bundler
  command: sudo gem install {{ item.name }}
  with_items:
   - { name: 'bundler'}

- name: Update ruby permissions  
  command: "sudo chown -R {{deploy_user}} /usr/local/lib/ruby"