#!/usr/bin/env ruby

require 'sidekiq'
require 'yaml'

arguments = ARGV[0..1]

settings = YAML.load_file('./config/secrets.yml')[ENV['RAILS_ENV']]
redis_host = settings['tb_redis']['host'] || 'localhost'
redis_port = settings['tb_redis']['port'] || 6379
redis_db = settings['redis_db'] || 0

Sidekiq.configure_client do |config|
  config.redis = { url: "redis://#{redis_host}:#{redis_port}/#{redis_db}" }
end

Sidekiq::Client.push('class' => 'CronWorker', 'args' => arguments)
