#!/usr/bin/env ruby

require 'sidekiq'
require 'yaml'

arguments = ARGV[0..1]

settings = YAML.load_file('./config/secrets.yml')

redis_db = settings[ENV['RAILS_ENV']]['redis_db'] || 0

Sidekiq.configure_client do |config|
  config.redis = { url: "redis://localhost:6379/#{redis_db}" }
end

Sidekiq::Client.push('class' => 'CronWorker', 'args' => arguments)
