- name: Add deploy user
  user: name={{deploy_user}} groups="sudo" shell="/bin/bash"

- name: Add RSA key to the remote host
  authorized_key: user={{ deploy_user }} key="{{ lookup('file', deploy_user_key)}}"

- name: Remove password
  command: passwd {{ deploy_user }} -d

- name: Update sudoers file 
  lineinfile: dest="/etc/sudoers" insertafter="EOF" line='{{ deploy_user }} ALL=(ALL) NOPASSWD:ALL' state="present"
